[FEATURE] - Implement GRPC executor
distribworks/dkron pull request #1049
Opened 2022-01-22 17:55 UTC by Espina2

Signed-off-by: Paulo Moura <itsme@paulomoura.com.pt>

2022-01-22 18:46 UTC, Espina2 commented
@vcastellm can you take a look?

2022-01-30 19:29 UTC, Espina2 commented
@vcastellm did you have the opportunity to take a look?

2022-01-31 20:52 UTC, vcastellm requested changes
LGTM overall but I'm missing documentation and some example use cases for this.

2022-03-13 12:23 UTC, Espina2 commented
@vcastellm I would love to merge this. Also is it possible to release after merge?

2022-03-16 23:39 UTC, vcastellm submitted a review, later dismissed
LGTM aside from the typo

2022-03-16 23:39 UTC, vcastellm commented on website/content/usage/executors/grpc.md
> +GRPC executor can send a request to an GRPC Server
```suggestion
GRPC executor can send a request to a GRPC Server
```

2022-03-16 23:40 UTC, vcastellm reviewed
Can you rebase with master?

2022-04-24 22:01 UTC, vcastellm approved these changes
Thanks @Espina2

2022-04-24 22:01 UTC, merged

2022-04-24 22:38 UTC, Espina2 commented
@vcastellm any way that we can make a release of this?

2022-04-26 10:24 UTC, vcastellm commented
@Espina2 It will be included in the next release

2022-04-26 11:08 UTC, Espina2 commented
> @Espina2 It will be included in the next release

When will that happen?

2022-04-26 20:47 UTC, vcastellm commented
@Espina2 I want to release `v3.2.0` in the following days.