fixed #1236 issue in main repo
distribworks/dkron pull request #1237
Opened 2022-12-09 20:01 UTC by edwsel

Fixed close connection when using grpc executor

2022-12-09 22:05 UTC, yvanoers requested changes
Minor styling request, but otherwise LGTM, thanks!

2022-12-11 14:06 UTC, edwsel commented on builtin/bins/dkron-executor-grpc/grpc.go
> +//	}
fixed

2022-12-11 14:24 UTC, yvanoers commented on builtin/bins/dkron-executor-grpc/grpc.go
> +//	}
Thanks, though, that was only the blank line - the indenting still doesn't align. with line 35.

2022-12-11 15:58 UTC, edwsel commented on builtin/bins/dkron-executor-grpc/grpc.go
> +//	}
Sorry, my ide auto format code, fixed

2022-12-11 17:47 UTC, vcastellm approved these changes
LGTM thx!

2022-12-11 17:53 UTC, merged