Github Action for release (binary and docker)
distribworks/dkron pull request #770
Opened 2020-05-22 10:01 UTC by fopina

2020-05-29 09:48 UTC, fopina commented
@victorcoder and no <3 for this one too ^^ ?
Took quite a few builds to get it right :hammer:

2020-06-18 23:27 UTC, fopinappb commented
out of curiosity @victorcoder , what leaves you uneasy on this PR? it's the simple change to GA that we discussed in gitter :)

2020-06-28 22:13 UTC, victorcoder commented
Sorry for the delay @fopina didn't have time to look into it until now

2020-08-27 16:26 UTC, meshchaninov commented
This works fine in rusberry pi 4 (ubuntu)

2020-09-03 16:52 UTC, victorcoder requested changes
Aside from the comment it LGTM, thanks!

2020-09-03 16:52 UTC, victorcoder commented on .github/workflows/release.yml
> +            -t ${DOCKER_REPO:-dkron/dkron}:${{ steps.prepare.outputs.tag_name }} \
This is missing the Major version tag

2020-09-04 08:26 UTC, victorcoder approved these changes
I'm merging this, I will add the tag

2020-09-04 08:26 UTC, merged

2020-09-04 16:11 UTC, fopina commented
Sorry, away from computer these days. Cool!