Replace boltdb with fast-store
distribworks/dkron pull request #976
Opened 2021-06-06 17:15 UTC by victorcoder

Replacing BoltDB with fast-store increased the speed of the Raft log operations enormously, allowing the user to choose the degree of duration in disk.

Under my tests, with the same degree of duration as boltdb (High) the speed is x2 but using the Mid duration, the default that sync to disk every second, the speed increases tenfold.

Considering that Dkron is not the source of truth for the data it stores, the cost-benefit of using less durability is high.

2021-06-07 21:17 UTC, yvanoers requested changes
Besides the comment, LGTM.
But does this change require users to do some kind of migration, or will this work transparently?

2021-06-07 21:17 UTC, yvanoers commented on dkron/agent.go
>  		// Create the BoltDB backend
You missed updating the comment here.

2021-06-08 07:35 UTC, victorcoder commented
Yes @yvanoers this is a breaking change, this is why this will be published in 4.x, you can not upgrade in place but it only requires of a rolling deploy.

2021-06-08 22:33 UTC, yvanoers approved these changes
LGTM!

2021-06-08 22:35 UTC, yvanoers commented
> Yes @yvanoers this is a breaking change, this is why this will be published in 4.x, you can not upgrade in place but it only requires of a rolling deploy.

Ok; is there, or will there be documentation on how to do that? I'm unaware of any.

2021-06-09 08:20 UTC, victorcoder commented
@yvanoers doc for upgrade strategies here https://dkron.io/usage/upgrade/#rolling-upgrade

2021-06-09 19:41 UTC, yvanoers commented
Ah yes, great!
And here's a PR to improve some of the text: #980 :)

2022-09-18 16:38 UTC, vcastellm commented
Superseded by #1172

2022-09-18 16:38 UTC, closed without merging